## Intializing a tensor

In [3]:
import torch

In [4]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32, requires_grad=True)

In [5]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [6]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [8]:
my_tensor.dtype

torch.float32

In [10]:
my_tensor.shape

torch.Size([2, 3])

In [11]:
my_tensor.device

device(type='cpu')

In [12]:
my_tensor.requires_grad

True

### Other common initialization methods

In [15]:
x = torch.empty(size = (3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x = torch.zeros((3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
x = torch.rand((3, 3))
x

tensor([[0.1560, 0.6804, 0.0248],
        [0.1621, 0.2328, 0.3713],
        [0.1312, 0.8602, 0.3921]])

In [18]:
x = torch.ones((3, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
x = torch.eye(5, 5)  # I, eye
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
x = torch.arange(start=0, end=5, step=1)
x

tensor([0, 1, 2, 3, 4])

In [21]:
x = torch.linspace(start=0.1, end=1, steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [22]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
x

tensor([[-0.7291, -0.1367,  0.7781,  0.4833, -0.3327]])

In [23]:
x = torch.empty(size=(1,5)).uniform_(0, 1)
x

tensor([[0.9495, 0.6348, 0.0669, 0.3223, 0.2061]])

In [24]:
x = torch.diag(torch.ones(3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### How to initialize and convert tensors to other types (int, float, double)

In [26]:
tensor = torch.arange(4)
print (tensor.bool())

tensor([False,  True,  True,  True])


In [27]:
print(tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [28]:
print (tensor.long()) #int64 (important)

tensor([0, 1, 2, 3])


In [29]:
print(tensor.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [31]:
print(tensor.float()) #floart32 (important)

tensor([0., 1., 2., 3.])


In [32]:
print(tensor.double())

tensor([0., 1., 2., 3.], dtype=torch.float64)


### Array to tensor conversion and vice-versa

In [34]:
import numpy as np
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)

In [35]:
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [37]:
np_array_back = tensor.numpy()

In [38]:
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Tensor Math & Comparison Operations

In [40]:
http://localhost:8889/notebooks/PyTorch.ipynb#Tensor-Math-&-Comparison-Operationsx = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [41]:
# addition
z1 = torch.empty(3)
torch.add(x,y, out=z1)

tensor([10., 10., 10.])

In [42]:
z2 = torch.add(x,y)
z = x+y

In [43]:
# Subtraction
z= x-y

In [44]:
# Division
z = torch.true_divide(x,y)

In [45]:
# inplace opeartions (contains underscore)
t = torch.zeros(3)
t.add_(x) 
t += x 

In [46]:
#Exponentation
z = x.pow(2)
z = x**2

In [48]:
#simple comparison
z = x>0
z = x<0

In [49]:
# matrix multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1, x2) # 2x3
x3 = x1.mm(x2)

In [50]:
#matrix exponentiation
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[6.3938, 4.6323, 4.7737, 3.7795, 3.1741],
        [6.0301, 4.4310, 4.5517, 4.0120, 2.6986],
        [4.4417, 3.1972, 3.3239, 3.0246, 1.9223],
        [5.0975, 3.5713, 3.7506, 3.0767, 2.4547],
        [3.7678, 2.7400, 2.8208, 2.4103, 1.7493]])


In [51]:
# element wise multiplication
z = x* y
print(z)

tensor([ 9, 16, 21])


In [52]:
# dot product
z = torch.dot(x,y)
print(z)

tensor(46)


In [53]:
# Batch Multiplication
batch = 32
n = 10
m = 20
p = 30

In [54]:
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)

In [55]:
out_bmm

tensor([[[4.7805, 4.8837, 3.9667,  ..., 4.8019, 5.2082, 5.4534],
         [4.4146, 4.5629, 4.6572,  ..., 3.8499, 4.4121, 4.7953],
         [5.0889, 4.3999, 4.6981,  ..., 4.5772, 5.1741, 5.2406],
         ...,
         [4.0458, 3.9125, 3.8999,  ..., 4.4360, 4.8358, 4.3934],
         [3.6940, 3.2427, 3.8396,  ..., 2.9258, 3.8155, 3.9726],
         [4.5519, 5.3283, 4.7096,  ..., 4.4202, 4.4525, 4.5239]],

        [[4.7763, 4.1991, 4.6244,  ..., 4.3381, 5.2677, 4.8971],
         [5.6189, 5.0790, 4.9844,  ..., 4.7783, 6.2111, 6.8862],
         [5.1686, 5.5085, 4.9107,  ..., 4.9978, 5.9862, 6.0985],
         ...,
         [6.0368, 5.8765, 5.4325,  ..., 4.2492, 6.9496, 6.8181],
         [5.4493, 4.4330, 4.7909,  ..., 4.9041, 6.0983, 5.8979],
         [5.3561, 5.5697, 5.2869,  ..., 5.6421, 6.9206, 7.0502]],

        [[6.4288, 6.2928, 6.2984,  ..., 6.1511, 5.1023, 3.6493],
         [6.2749, 4.9285, 4.8435,  ..., 5.3891, 5.3797, 3.2231],
         [5.8847, 4.8372, 4.9931,  ..., 5.3765, 4.7601, 3.

In [56]:
# Example of broadcasting 
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
z = x1 - x2

In [58]:
# Other useful tensor operation
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x)
z = torch.argmax(x, dim=0)
z = torch.argmin(x, dim=0)
mean_x = torch.mean(x.float(), dim=0)
z = torch.eq(x,y)
print(z)

tensor([False, False, False])


In [59]:
sorted_y, indices = torch.sort(y, dim=0, descending=False)

In [60]:
z = torch.clamp(x, min=0)

## Tensor Indexing

In [61]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

In [62]:
print(x[0].shape) # x[0,:]

torch.Size([25])


In [63]:
print(x[:, 0].shape)

torch.Size([10])


In [64]:
print(x[2, 0:10]) # 0:10 -> [0,1,2, ... 9]
x[0,0] = 100

tensor([0.7874, 0.6456, 0.0322, 0.7229, 0.8907, 0.2296, 0.9385, 0.9899, 0.0313,
        0.6049])


In [65]:
# Fancy Indexing
x= torch.arange(10)
indices = [2, 5, 8]
print(x[indices])

tensor([2, 5, 8])


In [66]:
x= torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows, cols].shape)

torch.Size([2])


In [68]:
#More advanced indexing
x = torch.arange(10)
print(x[(x<2) | (x>8)])

tensor([0, 1, 9])


In [72]:
print([x.remainder(2) ==0])

[tensor([ True, False,  True, False,  True, False,  True, False,  True, False])]


In [73]:
# useful operations
print(torch.where(x>5, x, x*2))

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [74]:
print(x.ndimension())

1


In [77]:
print(x.numel())

10


### Tensor Reshaping

In [78]:
x = torch.arange(9)
x_3x3 = x.view(3, 3)
print(x_3x3)

x_3x3 = x.reshape(3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [79]:
y = x_3x3.t()  # Transpose the matrix
print(y)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [81]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))

print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)


torch.Size([4, 5])
torch.Size([2, 10])


In [82]:
z = x1.view(-1)
print(z.shape)

batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)


torch.Size([10])
torch.Size([64, 10])


In [83]:
x = torch.arange(10)  # [10]
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)



torch.Size([1, 10])
torch.Size([10, 1])


In [84]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)  # 1x1x10

z = x.squeeze(1)
print(z.shape)


torch.Size([1, 10])
